### ISSUE TITLE
Conductivity calibration

### ISSUE THREAD

**Issue by gheleguen** [OceanographyforEveryone/OpenCTD#30]
Hi everyone, 

I made an open CTD for an antarctic expedition. This one must leave before 1st September. 
All is ok. I have just a problem with conductivity calibration. 
When I send c,0 or other command. I didn't got any response. 
The response of conductivity sensor in fresh water is around 300. Is it µS/cm ? 

The baud range is ok and TX and RXpin also right.

I work for an other job with teensy 3.6 board. I think Arduino IDE work with it's SoftwareSerial librairies. 

My Hardware is EZO board and mini conductivity probe k1.0. 

Excuse my english level. I'm french.

Best regards

Guillaume Leguen

**Comment by IanTBlack** [comment]
Hello Guillaume,

The documentation for the EC EZO can be confusing. It's been a while since I have built a CTD so I just went through it again.

When you send a "c,0", you are telling the EC EZO to stop auto sampling when in UART mode. If you have responses turned off with the "OK,0" command, then you won't get a string "OK" at the end of each response. To turn on responses, enter "OK,1".

Did you try sending a "R" command after turning off auto sampling? That should return a reading. To turn on auto sampling when you are done with the calibration, enter "c,1".

Given the accuracy of the sensor, I would say 300 uS/cm is reasonable for fresh water. Did you try it in distilled water?

Cheers,
- Ian
________________________________
From: gheleguen ***@***.***>
Sent: Monday, August 9, 2021, 04:13
To: OceanographyforEveryone/OpenCTD
Cc: Subscribed
Subject: [OceanographyforEveryone/OpenCTD] Conductivity calibration (#30)


[This email originated from outside of OSU. Use caution with links and attachments.]

Hi everyone,

I made an open CTD for an antarctic expedition. This one must leave before 1st September.
All is ok. I have just a problem with conductivity calibration.
When I send c,0 or other command. I didn't got any response.
The response of conductivity sensor in fresh water is around 300. Is it µS/cm ?

The baud range is ok and TX and RXpin also right.

I work for an other job with teensy 3.6 board. I think Arduino IDE work with it's SoftwareSerial librairies.

My Hardware is EZO board and mini conductivity probe k1.0.

Excuse my english level. I'm french.

Best regards

Guillaume Leguen

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOceanographyforEveryone%2FOpenCTD%2Fissues%2F30&data=04%7C01%7Cian.black%40oregonstate.edu%7C58f4089df9e2493d016e08d95b26bf21%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637641044234673921%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0JU1wewvIV7cywzYQysH7KmJ%2FgBzqIKjT8mmb%2FYqt8E%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGU4ACLCUFKCJGQJQIKBQHTT36Z6LANCNFSM5BZZOBKA&data=04%7C01%7Cian.black%40oregonstate.edu%7C58f4089df9e2493d016e08d95b26bf21%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637641044234683877%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vaE7qVEIqT5x6i%2FuaKvM5EByIdM9YcVPgvJ5Isah5Hg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cian.black%40oregonstate.edu%7C58f4089df9e2493d016e08d95b26bf21%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637641044234683877%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=P05cpLCnWUwC%2FYet1c%2Bu0OIsKYMnf%2FtJcFqR1loxqmQ%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cian.black%40oregonstate.edu%7C58f4089df9e2493d016e08d95b26bf21%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637641044234683877%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Z4Nky3UgFbtgw4mOIbkswcKQvTqeuPKWdFxN%2Br6dZVI%3D&reserved=0>.


Get Outlook for Android<https://aka.ms/AAb9ysg>

**Comment by gheleguen** [comment]
Hi Ian,

Really thanks for your queekly response. 
It's working. But in the first time it didn't working. I don't know why. 
But my CTD is calibrated. 

It's bizare but it's ok ;-)

Have a good day

Guillaume

**Comment by IanTBlack** [comment]
That's great. I'm glad it is working. Sometimes it is as simple as restarting the whole thing!

I am interested to see how you use the CTD in Antarctica.  Keep us updated!
________________________________

**Comment by DrAndrewThaler** [comment]
Hello,

Glad to hear you got it working. I've also occasionally had issues with the serial connection while calibrating the conductivity probe, but find a reset will get it moving again. The good news is you shouldn't have to calibrate it very often. 

It is  µS/cm. 

Make sure you reenabled autosampling before re-flashing the OpenCTD software (and that you edited out the three lines of diagnostic code that pause the sensors until a serial connection is established). 

All the best and looking forward to seeing what you do in Antarctica!
